"""empty message

Revision ID: 0ac9c1e31e87
Revises: 
Create Date: 2022-01-21 13:27:42.374440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ac9c1e31e87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'date_of_birth')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('date_of_birth', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
